### ISSUE TITLE
Tanay Review Ticket

### ISSUE THREAD

**Issue by connorw72** [connorw72/food#44]
- [ ] Individual Grade:
- [ ] 1. Attendance, tutorial makeup if missing time, activity, individual questions, work habits, tutorial if behind.
- [ ] 2. Individual Runtime review on About Page progress/quality.
- [ ] 3. Individual Analytics (Issues with Tangibles, Commits)
- [ ] 4. CB progress, focus is on CB-exam MCQ test and improvement plan
- [ ] 5. Expertise in one or more of the following...  Procedures, Blueprint, Jekyll, Deployment Certbot, Databases, Wikie Policies, Branching strategies, SCSS, Async with Fetch

**Comment by TANAY101405** [comment]
1. I have come to class everyday this week and participated in the TPT exercises and paid attention to the Tech-talks
2. I attempted to make a hangman page, but I added a dark mode button to our navbar.
3. I have commits to the main branch involving my PBL work for this week.
4. I completed the mcq with corrections and took notes on the Collegeboard Units.
5.  Worked on fixing the pull-requests because I had an error with the API's on my version. I was able to figure out how to just push my code from my branch to the main without any errors, so I had an expertise in Branching Strategies. I also worked on updating our deployed website and looked over the notes so I was an expertise with deployment certbot.
6. I think I deserve a 4.25/5 because I was not able to get the hangman game working, but I completed the dark mode feature. Also, I was not able to get expertise in databses, blueprints, or wiki policies.

**Comment by TANAY101405** [comment]
I think I deserve a 4.5/5 because I was able to integrate technicals for a pet history page and darkmode navbar, but struggled with finishing the hangman page. Next week, my goal is to work with our group on setting up a database and improving usage of Crud and SQL. I also hope to set up a style file so that it makes our layouts look nicer.
