### ISSUE TITLE
Colin Review Ticket

### ISSUE THREAD

**Issue by connorw72** [connorw72/food#48]
- [ ] Individual Grade:
- [ ] 1. Attendance, tutorial makeup if missing time, activity, individual questions, work habits, tutorial if behind.
- [ ] 2. Individual Runtime review on About Page progress/quality.
- [ ] 3. Individual Analytics (Issues with Tangibles, Commits)
- [ ] 4. CB progress, focus is on CB-exam MCQ test and improvement plan
- [ ] 5. Expertise in one or more of the following...  Procedures, Blueprint, Jekyll, Deployment Certbot, Databases, Wikie Policies, Branching strategies, SCSS, Async with Fetch

**Comment by KoolKidKai** [comment]
1. I have come to class prepared and ready to learn everyday, and even had extra work this week with my role as TO. I helped the OO's with the week's TPT. I think I have worked very hard this week both in class and out of class.

2. A clock is up and running in the navbar, and I have also been experimenting with an image carousel and Jekyll web pages. I don't think I understand the usefulness or purpose of Jekyll though. It seems unnecessary.

3. All commits and tangibles are found on the deployed site and the commits tabs within the readMe

4. All CB work has been finished and uploaded to pair journals. I also was assigned to teach the class about binary search for this week's TPT

5. Due to previous work I feel that I have expertise in Databases and Async processes. I also have expertise in branching as our group has made a solid procedure for pushing and pulling to the main and from branches. I started experimenting with jekyll and SCSS, but I don't consider myself an expert on any of these topics.

6. I would give myself a 4.25 because I don't think my jekyll pages nor my image carousel experiments actually fully work. The only fully functional PBL I've added this week was a clock to the navbar. Otherwise, I have fulfilled all parts of my role, personally and for the team.
